[package]
name = "cryptgeon"
version = "2.3.0-beta.5"
authors = ["cupcakearmy <hi@nicco.io>"]
edition = "2021"

[[bin]]
name = "cryptgeon"
path = "src/main.rs"

[registries.crates-io]
protocol = "sparse"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
actix-files = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
lazy_static = "1"
ring = "0.16"
bs62 = "0.1"
byte-unit = "4"
dotenv = "0.15"
mime = "0.3"
env_logger = "0.9"
redis = "0.21.5"
